apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: foundation-internal-security-otterdog
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
      - image: redis:7.2.4-alpine
        name: redis
        args: ["--save", "\"\"", "--loglevel", "warning"]
        ports:
          - containerPort: 6379
#        volumeMounts:
#          - name: "pvol"
#            mountPath: "/data"
#            subPath: "cache"
#      volumes:
#        - name: "pvol"
#          persistentVolumeClaim:
#            claimName: "otterdog-pvc"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: foundation-internal-security-otterdog
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    run: redis
