apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: otterdog-staging-env
  namespace: foundation-internal-security-otterdog
data:
  env: |
    DEBUG=True
    BASE_URL=https://otterdog-staging.eclipse.org
    APP_ROOT=/app/work
    CACHE_CONTROL=True
    OTTERDOG_CONFIG_OWNER=EclipseFdn
    OTTERDOG_CONFIG_REPO=otterdog-staging-configs
    OTTERDOG_CONFIG_PATH=otterdog.json
    OTTERDOG_CONFIG_TOKEN={{IT/CSI/otterdog/staging/otterdog_config_token}}
    MONGO_URI=mongodb://mongodb-staging:27017/otterdog
    GITHUB_ADMIN_TEAMS=eclipsefdn-security,eclipsefdn-releng
    GITHUB_WEBHOOK_ENDPOINT=/github-webhook/receive
    GITHUB_WEBHOOK_SECRET={{IT/CSI/otterdog/staging/github_webhook_secret}}
    GITHUB_WEBHOOK_VALIDATION_CONTEXT=eclipsefdn/otterdog-validation
    GITHUB_WEBHOOK_SYNC_CONTEXT=eclipsefdn/otterdog-sync
    GITHUB_OAUTH_CLIENT_ID=6d3a8a53c85faa425308
    GITHUB_OAUTH_CLIENT_SECRET={{IT/CSI/otterdog/staging/oauth_client_secret}}
    GITHUB_APP_ID=1140038
    GITHUB_APP_PRIVATE_KEY=/app/work/config/app.key
    DEPENDENCY_TRACK_URL=http://dependency-track-api-server.foundation-sbom.svc.cluster.local:8080
    DEPENDENCY_TRACK_TOKEN={{IT/CSI/otterdog/staging/dependency_track_token}}
---
apiVersion: "v1"
kind: "Secret"
type: Opaque
metadata:
  name: otterdog-staging-secrets
  namespace: foundation-internal-security-otterdog
data:
  app.key: |
    {{IT/CSI/otterdog/staging/github_app_key:4}}
