kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-staging-pvc
  namespace: foundation-internal-security-otterdog
  labels:
    app: redis
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-staging-pvc
  namespace: foundation-internal-security-otterdog
  labels:
    app: mongodb
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cephfs
  volumeMode: Filesystem
