name: Build page
on:
  push:
    branches: [ "main" ]
    paths:
     - '.github/workflows/build_page.yml'
     - 'otterdog.json'
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create list of projects
        run: |
          OUTPUT='./docs/orgs.csv'
          cat <<EOT > ${OUTPUT}
          Eclipse project,GitHub organization,Otterdog configuration
          EOT
          for org in $(jq -c '.organizations[]' < otterdog.json); do
            GITHUB_ID=$(echo $org | jq -r '.github_id')
            ECLIPSE_PROJECT=$(echo $org | jq -r '.eclipse_project')
            echo "[${ECLIPSE_PROJECT}](https://projects.eclipse.org/projects/${ECLIPSE_PROJECT}),[${GITHUB_ID}](https://github.com/${GITHUB_ID}),[${GITHUB_ID}.jsonnet](https://github.com/${GITHUB_ID}/.eclipsefdn/blob/main/otterdog/${GITHUB_ID}.jsonnet) |" >> ${OUTPUT}
          done
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-table-reader-plugin
      - name: Build with Mkdocs
        run: mkdocs build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
